version: '3.1'
services:
  stats-server:
    build: statistic/
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats-db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=CHS2t1062

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHS2t1062

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
