version: '3.1'
services:

  stats-server:
    build: statistic/server
    image: stats-server
    container_name: stats-container
    ports:
      - "9090:9090"
    depends_on:
      - ewm-service
      - stats-db


    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db


  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHS2t1062


  ewm-service:
    build: service
    image: main-service
    container_name: ewm_main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main-db



  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-db-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHS2t1062



