CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(250) UNIQUE                     NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (category_id)
);
