CREATE TABLE IF NOT EXISTS hits
(
    hit_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(250)                            NOT NULL,
    uri       VARCHAR(250)                            NOT NULL,
    ip        VARCHAR(250)                            NOT NULL,
    timestamp VARCHAR(250)                            NOT NULL,

    CONSTRAINT pk_request PRIMARY KEY (hit_id)
);
